# Generated by Django 4.2.7 on 2025-06-29 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'US30 Standard', 'EURUSD Aggressive')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this trading configuration')),
                ('inp_AllowedSymbol', models.CharField(default='US30', help_text='Allowed Symbol for trading', max_length=20)),
                ('inp_StrictSymbolCheck', models.BooleanField(default=True, help_text='Enable Strict Symbol Validation')),
                ('inp_SessionStart', models.CharField(default='08:45', help_text='Session Start Time (HH:MM format)', max_length=5)),
                ('inp_SessionEnd', models.CharField(default='10:00', help_text='Session End Time (HH:MM format)', max_length=5)),
                ('inp_FibLevel_1_1', models.DecimalField(decimal_places=5, default=1.325, help_text='Fibonacci Level 1.1', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_1_05', models.DecimalField(decimal_places=5, default=1.05, help_text='Fibonacci Level 1.05 (Buy Entry)', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_1_0', models.DecimalField(decimal_places=5, default=1.0, help_text='Fibonacci Level 1.0 (Session High)', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_PrimaryBuySL', models.DecimalField(decimal_places=5, default=-0.05, help_text='Primary Buy Stop Loss Level', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_PrimarySellSL', models.DecimalField(decimal_places=5, default=1.05, help_text='Primary Sell Stop Loss Level', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_HedgeBuy', models.DecimalField(decimal_places=5, default=1.05, help_text='Hedging Buy Entry Level', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_HedgeSell', models.DecimalField(decimal_places=5, default=-0.05, help_text='Hedging Sell Entry Level', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_HedgeBuySL', models.DecimalField(decimal_places=5, default=0.0, help_text='Hedging Buy Stop Loss Level', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_HedgeSellSL', models.DecimalField(decimal_places=5, default=1.0, help_text='Hedging Sell Stop Loss Level', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_0_0', models.DecimalField(decimal_places=5, default=0.0, help_text='Fibonacci Level 0.0 (Session Low)', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_Neg_05', models.DecimalField(decimal_places=5, default=-0.05, help_text='Fibonacci Level -0.05 (Sell Entry)', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_Neg_1', models.DecimalField(decimal_places=5, default=-0.325, help_text='Fibonacci Level -0.325 (Sell TP)', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_HedgeBuyTP', models.DecimalField(decimal_places=5, default=1.3, help_text='Hedging Buy Take Profit Level', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_FibLevel_HedgeSellTP', models.DecimalField(decimal_places=5, default=-0.3, help_text='Hedging Sell Take Profit Level', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inp_PrimaryPendingTimeout', models.PositiveIntegerField(default=30, help_text='Primary Order Pending Timeout (minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('inp_PrimaryPositionTimeout', models.PositiveIntegerField(default=60, help_text='Primary Position Timeout (minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('inp_HedgingPendingTimeout', models.PositiveIntegerField(default=30, help_text='Hedging Order Pending Timeout (minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('inp_HedgingPositionTimeout', models.PositiveIntegerField(default=60, help_text='Hedging Position Timeout (minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active and can be assigned to licenses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trading Configuration',
                'verbose_name_plural': 'Trading Configurations',
                'ordering': ['name'],
            },
        ),
    ]
