# Generated by Django 4.2.7 on 2025-06-30 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_AllowedSymbol',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_0_0',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_1_0',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_1_05',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_1_1',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_HedgeBuy',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_HedgeBuySL',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_HedgeBuyTP',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_HedgeSell',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_HedgeSellSL',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_HedgeSellTP',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_Neg_05',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_Neg_1',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_PrimaryBuySL',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_FibLevel_PrimarySellSL',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_HedgingPendingTimeout',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_HedgingPositionTimeout',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_PrimaryPendingTimeout',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_PrimaryPositionTimeout',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_SessionEnd',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_SessionStart',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_StrictSymbolCheck',
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='allowed_symbol',
            field=models.CharField(default='US30', help_text='Allowed Symbol for trading', max_length=20),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_hedge_buy_tp',
            field=models.DecimalField(decimal_places=5, default=1.3, help_text='Hedging Buy Take Profit', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_hedge_sell_tp',
            field=models.DecimalField(decimal_places=5, default=-0.3, help_text='Hedging Sell Take Profit', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_level_hedge_buy',
            field=models.DecimalField(decimal_places=5, default=1.05, help_text='Hedging Buy Entry', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_level_hedge_buy_sl',
            field=models.DecimalField(decimal_places=5, default=0.0, help_text='Hedging Buy Stop Loss', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_level_hedge_sell',
            field=models.DecimalField(decimal_places=5, default=-0.05, help_text='Hedging Sell Entry', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_level_hedge_sell_sl',
            field=models.DecimalField(decimal_places=5, default=1.0, help_text='Hedging Sell Stop Loss', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_primary_buy_entry',
            field=models.DecimalField(decimal_places=5, default=1.05, help_text='Primary Buy Entry', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_primary_buy_sl',
            field=models.DecimalField(decimal_places=5, default=-0.05, help_text='Primary Buy Stop Loss', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_primary_buy_tp',
            field=models.DecimalField(decimal_places=5, default=1.325, help_text='Primary Buy Take Profit (Buy TP)', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_primary_sell_entry',
            field=models.DecimalField(decimal_places=5, default=-0.05, help_text='Primary Sell Entry', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_primary_sell_sl',
            field=models.DecimalField(decimal_places=5, default=1.05, help_text='Primary Sell Stop Loss', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_primary_sell_tp',
            field=models.DecimalField(decimal_places=5, default=-0.325, help_text='Primary Sell Take Profit (Sell TP)', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_session_high',
            field=models.DecimalField(decimal_places=5, default=1.0, help_text='Session High', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='fib_session_low',
            field=models.DecimalField(decimal_places=5, default=0.0, help_text='Session Low', max_digits=8, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='hedging_pending_timeout',
            field=models.PositiveIntegerField(default=30, help_text='Hedging Order Pending Timeout (minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='hedging_position_timeout',
            field=models.PositiveIntegerField(default=60, help_text='Hedging Position Timeout (minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='primary_pending_timeout',
            field=models.PositiveIntegerField(default=30, help_text='Primary Order Pending Timeout (minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='primary_position_timeout',
            field=models.PositiveIntegerField(default=60, help_text='Primary Position Timeout (minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='session_end',
            field=models.CharField(default='10:00', help_text='Session End Time (HH:MM format)', max_length=5),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='session_start',
            field=models.CharField(default='08:45', help_text='Session Start Time (HH:MM format)', max_length=5),
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='strict_symbol_check',
            field=models.BooleanField(default=True, help_text='Enable Strict Symbol Validation'),
        ),
    ]
