# Generated by Django 4.2.7 on 2025-06-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_AllowedSymbol',
            new_name='allowed_symbol',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_0_0',
            new_name='fib_level_0_0',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_1_0',
            new_name='fib_level_1_0',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_1_05',
            new_name='fib_level_1_05',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_1_1',
            new_name='fib_level_1_1',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_HedgeBuy',
            new_name='fib_level_hedge_buy',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_HedgeBuySL',
            new_name='fib_level_hedge_buy_sl',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_HedgeBuyTP',
            new_name='fib_level_hedge_buy_tp',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_HedgeSell',
            new_name='fib_level_hedge_sell',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_HedgeSellSL',
            new_name='fib_level_hedge_sell_sl',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_HedgeSellTP',
            new_name='fib_level_hedge_sell_tp',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_Neg_05',
            new_name='fib_level_neg_05',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_Neg_1',
            new_name='fib_level_neg_1',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_PrimaryBuySL',
            new_name='fib_level_primary_buy_sl',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_FibLevel_PrimarySellSL',
            new_name='fib_level_primary_sell_sl',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_HedgingPendingTimeout',
            new_name='hedging_pending_timeout',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_HedgingPositionTimeout',
            new_name='hedging_position_timeout',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_PrimaryPendingTimeout',
            new_name='primary_pending_timeout',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_PrimaryPositionTimeout',
            new_name='primary_position_timeout',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_SessionEnd',
            new_name='session_end',
        ),
        migrations.RenameField(
            model_name='tradingconfiguration',
            old_name='inp_StrictSymbolCheck',
            new_name='strict_symbol_check',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='inp_SessionStart',
        ),
        migrations.AddField(
            model_name='tradingconfiguration',
            name='session_start',
            field=models.CharField(default='08:45', help_text='Session Start Time (HH:MM format)', max_length=5),
        ),
    ]
