# Generated by Django 4.2.7 on 2025-07-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_remove_tradingconfiguration_inp_allowedsymbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_hedge_buy_tp',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_hedge_sell_tp',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_level_hedge_buy',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_level_hedge_buy_sl',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_level_hedge_sell',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_level_hedge_sell_sl',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_primary_buy_entry',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_primary_buy_sl',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_primary_buy_tp',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_primary_sell_entry',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_primary_sell_sl',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_primary_sell_tp',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_session_high',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='fib_session_low',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='session_end',
        ),
        migrations.RemoveField(
            model_name='tradingconfiguration',
            name='session_start',
        ),
        migrations.AlterField(
            model_name='tradingconfiguration',
            name='name',
            field=models.CharField(help_text="Configuration name (e.g., 'Standard Config', 'Aggressive Setup')", max_length=100, unique=True),
        ),
    ]
