# Generated by Django 4.2.7 on 2025-06-29 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import licenses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Client's first name", max_length=50)),
                ('last_name', models.CharField(help_text="Client's last name", max_length=50)),
                ('country', models.CharField(help_text="Client's country", max_length=100)),
                ('email', models.EmailField(blank=True, help_text="Client's email address (optional)", max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text="Client's phone number (optional)", max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(default=licenses.models.generate_license_key, help_text='Unique license key for the trading robot', max_length=64, unique=True)),
                ('system_hash', models.CharField(blank=True, help_text='Primary trading account identifier (set on first use)', max_length=128, null=True, unique=True)),
                ('account_hash', models.CharField(blank=True, help_text='Hashed account login ID (for tracking account login changes)', max_length=128, null=True)),
                ('account_hash_history', models.JSONField(blank=True, default=licenses.models.default_account_hash_history, help_text='History of account hash changes with timestamps')),
                ('broker_server', models.CharField(blank=True, help_text='Broker server address (set on first use)', max_length=100, null=True)),
                ('account_trade_mode', models.IntegerField(choices=[(0, 'Demo Account'), (1, 'Restricted Account'), (2, 'Live Account')], default=0, help_text='Trading mode: Demo, Restricted, or Live')),
                ('expires_at', models.DateTimeField(help_text='License expiration date and time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the license is currently active')),
                ('first_used_at', models.DateTimeField(blank=True, help_text='When the license was first used by trading bot', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When the license was last used by trading bot', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this license has been used')),
                ('daily_usage_count', models.PositiveIntegerField(default=0, help_text='Number of uses today (resets daily)')),
                ('last_reset_date', models.DateField(auto_now_add=True, help_text='Last date when daily usage was reset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client who owns this license', on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licenses.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_licenses', to=settings.AUTH_USER_MODEL)),
                ('trading_configuration', models.ForeignKey(blank=True, help_text='Trading configuration for this license', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='configurations.tradingconfiguration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['license_key'], name='licenses_li_license_46e8fe_idx'), models.Index(fields=['system_hash'], name='licenses_li_system__162b11_idx'), models.Index(fields=['expires_at'], name='licenses_li_expires_2124f9_idx'), models.Index(fields=['is_active'], name='licenses_li_is_acti_8b9932_idx'), models.Index(fields=['account_trade_mode'], name='licenses_li_account_62effa_idx'), models.Index(fields=['last_used_at'], name='licenses_li_last_us_263ae7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_name', 'first_name'], name='licenses_cl_last_na_b8cd1c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['country'], name='licenses_cl_country_1ffb2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('first_name', 'last_name', 'country')},
        ),
    ]
