# Generated by Django 4.2.7 on 2025-07-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='system_hash',
            field=models.CharField(blank=True, help_text='Primary trading account identifier (set on first use)', max_length=128, null=True),
        ),
    ]
